### ISSUE TITLE
Great PKG and a very simple beginner Question

### ISSUE THREAD

**Issue by sfd99** [coolbutuseless/tickle#3]
**Hi Mike!,**

_tickle() = great_ 
Have  a very, very simple beginner Question,
(if you don't mind).

In your 1st **"Hello World"** example:

```
library(tickle)

value <- reactive_dbl(40)

ui_spec <- tic_window(
  title = "Hello World", 
  tic_row(
    tic_col(
      tic_button("Hello", command = function() {message("Hello")}, style = 'primary'),
      tic_button("World", command = function() {message("World")})
    ),
    tic_col(
      tic_slider(value),
      tic_label(textvariable = value)
    )
  )
)

win <- render_ui(ui_spec)
```

**I'd like to:**
 -  use the slider to select a value, (ie: select 30)
 -  multiply it by 2 ( w/ a command _inside_ the above tickle script)
 -  display the final  calc result **in the Rstudio Console:**   60.

Read the tutorial
but can't find a way.
_Help!_  

**SFd99
latest R, Rstudio, tickle 011 PKG
Ubuntu Linux 20.04.**

**Comment by hinkelman** [comment]
I'm also newly exploring `tickle`, but if I understand correctly, you just need to add `value() * 2` at the end of the code:

```
library(tickle)

value <- reactive_dbl(40)

ui_spec <- tic_window(
  title = "Hello World", 
  tic_row(
    tic_col(
      tic_button("Hello", command = function() {message("Hello")}, style = 'primary'),
      tic_button("World", command = function() {message("World")})
    ),
    tic_col(
      tic_slider(value),
      tic_label(textvariable = value)
    )
  )
)

win <- render_ui(ui_spec)

value() * 2
```

**Comment by sfd99** [comment]
**Hi Travis Hinkelman!**

Thanks for the quick reply.

Yes,
your suggestion does display:
  80
in the Rstudio Console Panel.

But
it didn't give me a chance
to actually first choose
  **another new value in the Slider**,
then multiply by 2.

I would like to **move the slider first **
to another value (say: 30)
and only then, multiply by 2...

Then,
the Rstudio Console Panel would show
the value: 60  (ie 30  * 2).

SFd99
latest R, Rstudio, tickle 011 PKG
Ubuntu Linux 20.04.
---

**Comment by coolbutuseless** [comment]
Thanks for filing the issue.

I've expanded the documentation to include a few more basic examples in the vignettes:  See https://coolbutuseless.github.io/package/tickle/articles/helloworld.html
