### ISSUE TITLE
Displaying HTML Widgets?

### ISSUE THREAD

**Issue by gfleetwood** [coolbutuseless/tickle#4]
Hi. I've been reading through the docs and trying out various functions, but can't get an html widget to display. Is it possible? This is the code I'm running for reference on R 4.2.1 on Ubuntu 20.04:

```
library(tickle)
library(diffr)

# I have two random text files that I supply here
file1 = file.choose()
file2 = file.choose()
diff = diffr(file1, file2, before = basename(file1), after = basename(file2))

happiness <- reactive_dbl(40)

col1 =   tic_col(
tic_slider(happiness),
tic_label(textvariable = happiness),
canvas_text(diff)
)

row = tic_row(col1)

ui_spec <- tic_window(title = "Hello World", row)
win <- render_ui(ui_spec)
```

PS: In `tic_label(textvariable = happiness)` how would I round the label to two decimal places?

**Comment by coolbutuseless** [comment]
Rounding a slider variable takes a bit of chicanery

* Put the `tic_slider` value into a reactive variable (as you've done)
* Also, call a command every time the slider changes to round this value and put the result back into the same reactive variable.

```
library(tickle)

happiness <- reactive_dbl(40)

slider_func <- function(...) {
  happiness(round(happiness(), 2))
}

col1 =   tic_col(
  tic_slider(happiness, command = slider_func),
  tic_label(textvariable = happiness)
)

row = tic_row(col1)

ui_spec <- tic_window(title = "Hello World", row)
win <- render_ui(ui_spec)

```

**Comment by coolbutuseless** [comment]
On the other matter: I don't think there is a modern/supported HTML widget for tcl/tk.

Happy to be proved wrong!

**Comment by gfleetwood** [comment]
Thanks. 

It seems like html for tcl/tk is implemented in Python's tkinter (https://stackoverflow.com/a/48909932), but I don't know the details.

**Comment by coolbutuseless** [comment]
Python `tkinterhtml` is a wrapper around `tkhtml3` which appears dead.

Summary: I can't see HTML widget support being added to `tickle`anytime in the near future.
